# Base configs
baseurl: "http://andarazoroflove.org/replicawatches"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "Adventures on DHgate"
subtitle: "Replicas: Some good; Some meh."
author: ""
header:
 title: "Replica Watches"
 subtitle: "wrist roll archive @ https://imgur.com/a/p4zREHM"
footer:
 name: ""
 bio: ""
 github: ""
web_design: ""
social_urls:
  facebook: ""
  twitter: ""
  instagram: ""
  dribbble: ""
  linkedin: ""
  github: ""
